before_script:
  -
  - git submodule update --init --recursive
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker run -v $(pwd):/site guidoffm/gohugoio-hugo -c hugo
  only:
  - master
  - tags


deploy:
  stage: deploy
  script:
    - mkdir ${pwd}/.aws
    - echo "[default]" > ${pwd}/.aws/credentials
    - echo "aws_access_key_id = ${AWS_ACCESS_KEY}" >> ${pwd}/.aws/credentials
    - echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ${pwd}/.aws/credentials
    - docker run -v ${pwd}/.aws:/root/.aws -v $(pwd)/public:/public --rm -it -e AWS_DEFAULT_REGION=us-east-2  amazon/aws-cli s3 sync /public/ s3://matthewkruse.com-root
  only:
    - master
    - tags