before_script:
  - git submodule update --init --recursive
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker run -v $(pwd):/site guidoffm/gohugoio-hugo -c hugo
    - docker run -v $(pwd)/public:/public --rm -it -e AWS_DEFAULT_REGION=us-east-2 -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY  amazon/aws-cli s3 sync /public/ s3://matthewkruse.com-root
  only:
  - master
  - tags
