stages:
  - build_site
  - deploy_site
  - build_pdf
  - deploy_pdf

before_script:
  - git submodule update --init --recursive
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_site:
  stage: build_site
  artifacts:
    untracked: true
  script:
    - docker run -u 996 -v $(pwd):/site guidoffm/gohugoio-hugo -c hugo
  only:
  - master
  - tags


deploy_site:
  stage: deploy_site
  dependencies:
    - build_site
  script:
    - mkdir $(pwd)/.aws
    - touch $(pwd)/.aws/credentials
    - echo "[default]" > `pwd`/.aws/credentials
    - echo "aws_access_key_id = ${AWS_ACCESS_KEY}" >> `pwd`/.aws/credentials
    - echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> `pwd`/.aws/credentials
    - docker run -v $(pwd)/.aws:/root/.aws -v $(pwd)/public:/public -e AWS_DEFAULT_REGION=us-east-2  amazon/aws-cli s3 sync /public/ s3://matthewkruse.com-root
  only:
    - master
    - tags


build_pdf:
  stage: build_pdf
  dependencies:
    - deploy_site
  script:
    - mkdir $(pwd)/pdf_files
    - docker run -e URL="https://matthewkruse.com" -e FILENAME="/pdf_files/matthew-kruse-resume.pdf" -v "$(pwd)"/pdf_files:/pdf_files git.datumhosting.com:4567/matt-kruse/pdf-generator/pdf-generator
  only:
    - master
    - tags
  when: delayed
  start_in: 30 seconds


deploy_pdf:
  stage: deploy_pdf
  dependencies:
    - build_pdf
  script:
    - mkdir $(pwd)/.aws
    - touch $(pwd)/.aws/credentials
    - echo "[default]" > `pwd`/.aws/credentials
    - echo "aws_access_key_id = ${AWS_ACCESS_KEY}" >> `pwd`/.aws/credentials
    - echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> `pwd`/.aws/credentials
    - docker run -v $(pwd)/.aws:/root/.aws -v $(pwd)/pdf_files:/pdf_files -e AWS_DEFAULT_REGION=us-east-2  amazon/aws-cli s3 sync /pdf_files/ s3://matthewkruse.com-root
  only:
    - master
    - tags
